#!/bin/bash

echo "PLEASE ENTER YOUR PIN :"
read -s PIN  
#SO HERE PIN IS VARIABLE , WHAT EVER YOU GIVE IN LINUX SERVER THAT WILL SAVE IN THI PIN VARIABLE THEN IT WILL DISPLAY IT AS IN BELOW LINE 
#ONE MORE THINIG USUALLY PIN SHOULD NOT DISPLY IF U DONT WANT TO DISPLAY PIN WHILE TYPING USE  "read -s" this commmand.
echo "YOUR PIN NUMBER IS :$PIN"