#!/bin/bash

EXACTDATE=$(DATE)
echo "the the exact execution date is :$EXACTDATE"

#SO HERE EXACTDATE IS VARIABLE IT STORING DATE VALUE IN IT AND IN 4TH LINE WE GIVEN $BEFOREW VARIABLE BECAUSE TO MAKE UNDERSTADE THE SHELL SCRIPT 
#DIFFERENCE OF  NORMAL TEXT AND VARIAVBBLE.