#!/bin/bash

MOVIES=("DHURANDHAR" "KALKI-2" "RRR" "DOCIOT")

echo "BLOCKBUSTER MOVIE IS $MOVIES(0)THIS MOVIE GOT A HUGE FAN BASE "
echo "$MOVIES(1)ITS NOT YET RELEASED"
echo "$MOVIES(2)FANTASTIC MOVIE"

echo "Over all most of my favourite movies are $MOVIES(@)"