#!/bin/bash

MOVIES=("DHURANDHAR" "KALKI-2" "RRR" "DOCIOT")

ECHO "BLOCKBUSTER MOVIE IS $MOVIES(0)THIS MOVIE GOT A HUGE FAN BASE "
ECHO "$MOVIES(1)ITS NOT YET RELEASED"
ECHO "$MOVIES(2)FANTASTIC MOVIE"

ECHO "Over all most of my favourite movies are $MOVIES(@)"